# To use this file rename it to `docker-compose.override.yml` or use it with the following command:
# `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d`
# See https://docs.docker.com/compose/reference/overview/#specifying-multiple-compose-files
version: '3.4'

services:
  php:
    user: "1000:1000"
    build:
      target: api_platform_php_dev
    environment:
    # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
    # Then PHPStorm will use the corresponding path mappings
      PHP_IDE_CONFIG: serverName=api-platform
      # See https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
      # The `remote_host` below may optionally be replaced with `remote_connect_back`
      #
      # Choose some other port than `9000`, as this one is already occupied by FPM
      # Make sure to also change your listening port in the IDE to this value
      XDEBUG_CONFIG: >-
        remote_enable=1
        remote_connect_back=1
        remote_port=9999
        idekey=PHPSTORM
          
  localstack:
    build:
      context: ./localstack
      target: api_localstack
    image: localstack/localstack
    ports:
    - "4567-4584:4567-4584"
    - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
    - SERVICES=${SERVICES- }
    - DEBUG=${DEBUG- }
    - DATA_DIR=${DATA_DIR- }
    - PORT_WEB_UI=${PORT_WEB_UI- }
    - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
    - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
    - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
    - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    - "/var/run/docker.sock:/var/run/docker.sock"
